### ISSUE TITLE
Canvas not loading on IOS 12.5.5

### ISSUE THREAD

**Issue by GregoireDucharme** [YanYuanFE/react-native-signature-canvas#257]
I am trying to use the canvas on an **IPhone 6** with **IOS 12.5.5**, and I am having issues.

The component does not seems to charge properly.
I am using the `<SignatureScreen/>` element. If I have two of them, chances are that the second one is gonna be working.

I have those warnings:

`Did not receive response to shouldStartLoad in time, defaulting to YES`

And

`startLoadWithResult invoked with invalid lockIdentifier: got 26356645, expected 16546544`

Also I try to `clearSignature` of a not properly loaded element I have this warning;

`Error evaluating injectedJavaScript: This is possibly due to an unsupported return type. Try adding true to the end of your injectedJavaScript string.`

I try to add `customHtml={(o} => {return o + 'true;'})` to my `signatureScreen`, but that doesn't seems to do anything.

I have found issues that seems related on react-native-webview, https://github.com/react-native-webview/react-native-webview/issues/124, but not quite sure what can I do with those infos.

If anyone has encountered this error, I'm all ears

Thanks in advance !

**Comment by anuraagy** [comment]
I'm having the same issue as well. Let me know if you found a fix yet!

**Comment by anuraagy** [comment]
I fixed this issue for myself once I setup the callback functions written in the Readme (onOK, onEnd, onGetData)

**Comment by GregoireDucharme** [comment]
Still not working on my side, but then issue seems to happen only in development mode.
The component is working correctly in my testflight app.

It sometimes works without problem on dev mode though, I think it depends on how elements we're loaded, not quite sure.

**Comment by anuraagy** [comment]
I wonder if it could be a network issue on the simulator? I ran into it not loading a couple of times due to that.

**Comment by GregoireDucharme** [comment]
Might be.
I'm not touching anything for now, if live app behave the same as testflight app, everything should be fine.
